### ISSUE TITLE
Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run

### ISSUE THREAD

**Issue by lanzone1** [Data-Marketing-School/matomo-configuration-tag#1]
When reviewing your template we've noticed that `gtmOnSuccess` and `gtmOnFailure` are called incorrectly. This is required so that users can sequence their tags correctly. What you have is:

```
injectScript(trackerURL, data.gtmOnSuccess(), data.gtmOnFailure(), trackerURL);
```
This will result in both `gtmOnSuccess` and `gtmOnFailure` always being called. 

I think what you want is (note the lack of parentheses):
```
injectScript(trackerURL, data.gtmOnSuccess, data.gtmOnFailure, trackerURL);
```
Otherwise, looks good.

**Comment by lucasgtm** [comment]
Thank you for your feedback, correction applied!
