### ISSUE TITLE
Documentation link is invalid

### ISSUE THREAD

**Issue by lanzone1** [Data-Marketing-School/matomo-configuration-tag#2]
Hi,

When reviewing your template, we noticed that the documentation link is invalid. https://www.data-marketing-school.com/documentation

Please fix that link. Otherwise, looks good. Thanks.

**Comment by lucasgtm** [comment]
Hello Andy, you already approved this template and I removed the link to the 404 documentation in this commit [697abb4](https://github.com/data-marketing-school/matomo-configuration-tag/commit/697abb47f56d371b0e8bd4209588b48fc5be593c)

**Comment by lanzone1** [comment]
Sorry for the mix up. It looks like it was an issue with our tooling. Thanks.

**Comment by lucasgtm** [comment]
Okay no worries, while you are on my github, I submitted 2 new matomo tag templates ([this one](https://github.com/data-marketing-school/matomo-ecommerce-tag) and [that one](https://github.com/data-marketing-school/matomo-server-tag)). :)
